`id` INT AUTO_INCREMENT PRIMARY KEY,
    `firstName` VARCHAR(255) NOT NULL,
    `lastName` VARCHAR(255) NOT NULL,
    `otherName` VARCHAR(255),
    `gender` ENUM('male', 'female', 'other') NOT NULL,
    `height` INT NOT NULL,
    `ageGroup` ENUM('child', 'adult', 'senior') NOT NULL,
    `healthConditions` TEXT,
    `medications` VARCHAR(255),
    `allergies` VARCHAR(255),
    `dietaryRestrictions` VARCHAR(255),
    `nationality` VARCHAR(255),
    `country` VARCHAR(255),
    `residentialAddress` VARCHAR(255),
    `postalAddress` VARCHAR(255),
    `maritalStatus` ENUM('single', 'married', 'divorced', 'widowed'),
    `profession` VARCHAR(255),
    `email` VARCHAR(255) NOT NULL,
    `emergencyContactName` VARCHAR(255),
    `emergencyContactPhone` VARCHAR(20),
    `personalPhone` VARCHAR(20),
    `bookingDate` DATE NOT NULL,
    `bookingTime` TIME NOT NULL,
    `purpose` TEXT,
    `numSeats` INT NOT NULL,
    `rating` INT,
    `agreement` TINYINT(1) NOT NULL
);